In [127]:
import numpy as np
import pandas as pd
import re
import nltk
import matplotlib.pyplot as plt
import xlrd 
#Exportar el archivo 
import pickle

%matplotlib inline

In [128]:
import pandas as pd
archivo = 'Train.xlsx'

data = pd.read_excel(archivo)
data.head()

Title  \
0                           Pésimo lugar   
1              No vayas a lugar de Eddie   
2           Mala relación calidad-precio   
3       Minusválido? ¡No te alojes aquí!   
4  Es una porqueria no pierdan su tiempo   

                                             Opinion  Polarity  Attraction  
0  Piensen dos veces antes de ir a este hotel, te...       1.0       Hotel  
1  Cuatro de nosotros fuimos recientemente a Eddi...       1.0  Restaurant  
2  seguiré corta y simple: limpieza\n- bad. Tengo...       1.0       Hotel  
3  Al reservar un hotel con multipropiedad Mayan ...       1.0       Hotel  
4  No pierdan su tiempo ni dinero, venimos porque...       1.0       Hotel

In [168]:
features = data.iloc[:,1].values
labels = data.iloc[:,3].values

In [169]:
processed_features=[]
for sentence in range(0, len(features)):
    #remove all the especial characteres
    processed_feature = re.sub(r'\W',' ',str(features[sentence]))
    
    #Remove all single characters
    processed_feature= re.sub(r'\s+[a-zA-Z]\s+',' ',processed_feature)
    
    #REMOVE SINGLE CHARACTERS FROM THE START
    
    processed_feature= re.sub(r'\^[a-zA-Z]\s+',' ',processed_feature)
    
    #SUBSTITUING MULTIPLE SPACES WITH SINGLE SPACE 
    processed_feature= re.sub(r'\s+',' ',processed_feature, flags = re.I)
    
    #REMOVING PREFIXED 'b'
    processed_feature= re.sub(r'^b\s+',' ',processed_feature)
    
    #CONTERTING TO LOWERCASE
    processed_feature = processed_feature.lower()
    processed_features.append(processed_feature)

In [170]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer (max_features=2500, min_df=7, max_df=0.8, stop_words=stopwords.words('spanish'))
processed_features = vectorizer.fit_transform(processed_features).toarray()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BRAYAN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [171]:
from sklearn.model_selection import train_test_split

X_train, X_test , y_train , y_test = train_test_split(processed_features, labels , test_size=0.2, random_state=0)

In [172]:
from sklearn.ensemble import RandomForestClassifier

text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)
text_classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=0)

In [174]:
predictions = text_classifier.predict(X_test)

In [175]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions)) 
print(accuracy_score(y_test, predictions))

[[ 983   13   29]
 [   6 3196   71]
 [  16   94 1634]]
              precision    recall  f1-score   support

  Attractive       0.98      0.96      0.97      1025
       Hotel       0.97      0.98      0.97      3273
  Restaurant       0.94      0.94      0.94      1744

    accuracy                           0.96      6042
   macro avg       0.96      0.96      0.96      6042
weighted avg       0.96      0.96      0.96      6042

0.9620986428334989


In [ ]:
# Con este modelo podemos identificar una precision de 96 % esta es muy alta y nos indica que es un modelo muy viable para utilizar con este tipo de datasets.

In [176]:
#Support Vector Machines

In [177]:
modelo = SVC(kernel='linear').fit(X_train, y_train)

In [178]:
predicciones = modelo.predict(X_test)
predicciones

array(['Hotel', 'Hotel', 'Restaurant', ..., 'Hotel', 'Restaurant',
       'Restaurant'], dtype=object)

In [179]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,predicciones))
print(classification_report(y_test,predicciones)) 
print(accuracy_score(y_test, predicciones))
svc_linear =accuracy_score(y_test, predicciones)

[[1004    3   18]
 [   7 3199   67]
 [   9   43 1692]]
              precision    recall  f1-score   support

  Attractive       0.98      0.98      0.98      1025
       Hotel       0.99      0.98      0.98      3273
  Restaurant       0.95      0.97      0.96      1744

    accuracy                           0.98      6042
   macro avg       0.97      0.98      0.97      6042
weighted avg       0.98      0.98      0.98      6042

0.9756703078450845


In [ ]:
# Con este modelo Support Vector Machines podemos identificar una precision de 97 % esta es mucho mas  alta que la anterior y nos indica que es un modelo mucho mas  viable para utilizar con este tipo de datasets.

In [180]:
#Decision Trees

In [181]:
from sklearn.tree import DecisionTreeClassifier
tree_predic = DecisionTreeClassifier().fit(X_train, y_train).predict(X_test)
tree_predic

array(['Hotel', 'Hotel', 'Hotel', ..., 'Hotel', 'Hotel', 'Restaurant'],
      dtype=object)

In [182]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,tree_predic))
print(classification_report(y_test,tree_predic)) 
print(accuracy_score(y_test, tree_predic))
tree_classifi =accuracy_score(y_test, tree_predic)

[[ 958   16   51]
 [  36 3015  222]
 [  36  223 1485]]
              precision    recall  f1-score   support

  Attractive       0.93      0.93      0.93      1025
       Hotel       0.93      0.92      0.92      3273
  Restaurant       0.84      0.85      0.85      1744

    accuracy                           0.90      6042
   macro avg       0.90      0.90      0.90      6042
weighted avg       0.90      0.90      0.90      6042

0.9033432638199271


In [ ]:
#Podemos identificar que el modelo Decision Trees es mucho menos efectivo que los otros dos con un 90 % de precision es muy bueno pero en comparacion con  Support Vector Machines decae un poco su recision. 

In [ ]:
#CONCLUSION : Podemos decir que Support Vector Machines es un modelo que nos ayuda a tener una precision mas viable para este tipo de datasets y el analisis de sus datos.